config/routes.rb
Promptly::Application.routes.draw do
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   :as => 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'pages#home'


  # match 'logout', :to => 'sessions#destroy', :as => "logout"
    authenticated :user do
      root :to => 'pages#home'
    end

  namespace :admin do
      as :super do
        root to: 'superdashboard#index', as: 'dashboard'
      end
      resources :superdashboard, only: [:index] do
        get :show_users
        get 'edit_user/:id', to: 'superdashboard#edit_user', as: :edit_user
        post 'edit_user/:id', to: 'superdashboard#update_user', as: :update_user
      end
    resources :organizations do
      match 'reminders#panel2a' => 'reminders#panel2a', :as => :sent_reminders
      match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
      match 'dashboard/report', :to => 'dashboard#report', :as => :report
      match 'dashboard/export(/:options)/notifications', :to => 'dashboard#export', :as => :dashboard_export
      resources :users
      resources :recipients
      resources :conversations
      resources :groups
      resources :messages
      resources :organizations
      resources :reminders do
        collection do
          post :confirm
        end
      end
    end

  end


  #project page
  match '/hsa'       => 'pages#hsa'
  match '/documents' => 'pages#documents'

  #autoresponse
  match '/handle-incoming-sms'  => 'auto_response#handle_incoming_sms'
  match '/handle-incoming-call' => 'auto_response#handle_incoming_call'
  match '/handle-input'         => 'auto_response#handle_input'
  match '/english-response'     => 'auto_response#english_response'
  match '/spanish-response'     => 'auto_response#spanish_response'
  match '/cantonese-response'   => 'auto_response#cantonese_response'
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
  attr_accessible :name, :phone, :reminder_ids, :conversation_ids, :group_ids, :organization_ids
  has_and_belongs_to_many :messages
  has_and_belongs_to_many :conversations
  has_and_belongs_to_many :groups
  has_and_belongs_to_many :organizations
  has_many :reminders
  has_many :messages, :through => :reminders

  accepts_nested_attributes_for :messages
  phony_normalize :phone, :default_country_code => 'US'
  validates :phone, :phony_plausible => true

  def phone_or_name
    name ? "#{name}" : "#{phone}"
  end

end

app/controllers/admin/recipients_controller.rb
class Admin::RecipientsController < OrgController

  before_filter :set_recipient!, only: [ :show, :edit, :update, :destroy ]
  # before_filter :standardize_numbers, only: [ :create, :update ]
  # before_filter :authenticate_user!
  load_and_authorize_resource

  # after_filter :log_conversation, only: [ :create, :update]
  # GET /recipients
  # GET /recipients.json
  def index
    @recipients = Recipient.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipients }
      format.js
    end
  end

  # GET /recipients/1
  # GET /recipients/1.json
  def show
    @recipient = Recipient.find(params[:id])
    # @conversations = @recipient.conversations.group("date")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipient }
    end
  end

  # GET /recipients/new
  # GET /recipients/new.json
  def new
    @recipient = Recipient.new
    # @recipient.notifications.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipient }
    end
  end

  # GET /recipients/1/edit
  def edit
  end

  # POST /recipients
  # POST /recipients.json
  def create
    @recipient = Recipient.new(params[:recipient])
    respond_to do |format|
      if @recipient.save
        format.js
        format.html { redirect_to @recipient, notice: 'Recipient was successfully created.' }
        format.json { render json: @recipient, status: :created, location: @recipient }
      else
        format.html { render action: "new" }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /recipients/1
  # PUT /recipients/1.json
  def update
    respond_to do |format|
      if @recipient.update_attributes(params[:recipient])
        format.html { redirect_to [:admin, @recipient], notice: 'Recipient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.json
  def destroy
    @recipient.destroy

    respond_to do |format|
      format.html { redirect_to organization_recipients_url(@organization.id) }
      format.json { head :no_content }
    end
  end

  def import
    Recipient.import(params[:file])
    redirect_to root_url, notice: "Users imported."
  end

  private

  def set_recipient!
    @recipient = Recipient.find(params[:id])
  end

end

app/helpers/recipients_helper.rb
module RecipientsHelper
	def notifications
		@recipient.notifications
	end

	def which_sender(phone_number)
		self_phone = ENV["TWILIO_NUMBER"]
		if phone_number[-10..-1] != self_phone
			sender = "recipient"
		else
			sender = "self"
		end
	end 


end

app/views/admin/recipients/_deliveries.erb
 <%= link_to delivery.send_date.to_s(:date_format), delivery_path(delivery.batch_id) %><br />

app/views/admin/recipients/_form.html.erb
<%= simple_form_for [:admin, @organization, @recipient]  do |f| %>
  <% if @recipient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipient.errors.count, "error") %> prohibited this recipient from being saved:</h2>

      <ul>
      <% @recipient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :phone, required: true %>
  <%= f.input :name, required: false %>

  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>  
<% end %>

app/views/admin/recipients/_reminders.erb
<p> <%= link_to reminder.send_date.to_s(:date_format), admin_organization_reminder_path(@organization,reminder.batch_id) %></p>

app/views/admin/recipients/edit.html.erb
<h1>Editing recipient</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_organization_recipient_path(@organization,@recipient) %> |
<%= link_to 'Back', admin_organization_recipients_path(@organization) %>

app/views/admin/recipients/index.html.erb
  <div class="row-fluid">
  <h3>All recipients</h3>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Phone number</th>
            <th>Reminders sent</th>
            <th>Reminder details</th>
            <th></th>
          </tr>
        </thead>
        <% @recipients.each do |recipient| %>
          <tr>
            <td><%= link_to number_to_phone(recipient.phone), [:admin, @organization, recipient] %></td>
            <td><%= render(:partial => 'reminders', :collection => recipient.reminders, :as => :reminder) || 'You have no reminders' %></td>
          <td><%= link_to 'Edit', edit_admin_organization_recipient_path(@organization,recipient), :class=>'btn btn-mini' %>  <%= link_to 'Delete', [:admin, @organization, recipient], method: :delete, data: { confirm: 'Are you sure?' }, :class=>'btn btn-danger btn-mini' %></td>
          </tr>
          <% end %>
        </table>
      <%= link_to 'New recipient', new_admin_organization_recipient_path(@organization), :class=>'btn btn-primary' %>
      </div>    
    </div>
  </div>
  
  

app/views/admin/recipients/new.html.erb
<h3>Enter your phone number and reminder date</h3>

<%= render 'form' %>

<%= link_to 'Back', organization_recipients_path(@organization) %>

app/views/admin/recipients/show.html.erb
<div class="row-fluid">
  <p id="notice"><%= notice %></p>

  <h1>
    <%= number_to_phone(@recipient.phone, :area_code => true) %>
  </h1>
</div>

<div class="row-fluid">

  <div class="span8">
    <div class="row-fluid">
      <div class="span12 headerSmall headerAqua">
        <span class="headerText">Recipient History</span>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12 conversation">
        <%= render(:partial => 'shared/show_conversation', :collection => @recipient.conversations, :as => :conversation) || 'No messages.' %>
      </div>
    </div>
  </div>

  <div class="span4 sidebar">
    <div class="row-fluid">
      <div class="span12 headerSmall headerAqua">
        <span class="headerText">Queued Reminders</span>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12 queued">
        <%= render(:partial => 'shared/queued_reminders', :collection => @recipient.reminders, :as => :reminder) || 'No queued reminders.' %>
      </div>
    </div>
  </div>

</div>