config/routes.rb
Promptly::Application.routes.draw do
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   :as => 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'pages#home'


  # match 'logout', :to => 'sessions#destroy', :as => "logout"
    authenticated :user do
      root :to => 'pages#home'
    end

  namespace :admin do
      as :super do
        root to: 'superdashboard#index', as: 'dashboard'
      end
      resources :superdashboard, only: [:index] do
        get :show_users
        get 'edit_user/:id', to: 'superdashboard#edit_user', as: :edit_user
        post 'edit_user/:id', to: 'superdashboard#update_user', as: :update_user
      end
    resources :organizations do
      match 'reminders#panel2a' => 'reminders#panel2a', :as => :sent_reminders
      match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
      match 'dashboard/report', :to => 'dashboard#report', :as => :report
      match 'dashboard/export(/:options)/notifications', :to => 'dashboard#export', :as => :dashboard_export
      resources :users
      resources :recipients
      resources :conversations
      resources :groups
      resources :messages
      resources :organizations
      resources :reminders do
        collection do
          post :confirm
        end
      end
    end

  end


  #project page
  match '/hsa'       => 'pages#hsa'
  match '/documents' => 'pages#documents'

  #autoresponse
  match '/handle-incoming-sms'  => 'auto_response#handle_incoming_sms'
  match '/handle-incoming-call' => 'auto_response#handle_incoming_call'
  match '/handle-input'         => 'auto_response#handle_input'
  match '/english-response'     => 'auto_response#english_response'
  match '/spanish-response'     => 'auto_response#spanish_response'
  match '/cantonese-response'   => 'auto_response#cantonese_response'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < OrgController
  before_filter :authorize
  include SmartListing::Helper::ControllerExtensions
  helper  SmartListing::Helper
	
  def index
    @this_org = Organization.find(@organization.id)
    @recipient = Recipient.all
    @recents = Conversation.organization(@organization.id).find(:all, :order => "date desc")
    @conversations = Conversation.organization(@organization.id).where("message_id is not null", :order => "date desc")
    @upcoming = Reminder.organization(@organization.id).upcoming
    @last_month = Conversation.organization(@organization.id).where("status =? and date >= ?", "sent", DateTime.now - 1.month ).count
    @this_year = Conversation.organization(@organization.id).where("status =? and date >= ?", "completed", "#{Time.now.year}0101").count
    @last_month_calls = Conversation.unique_calls_last_month(@this_org.phone_number)
    @calls = Conversation.organization(@organization.id).where("call_id is not null and message_id is null", :order => "date desc")
    @last_month == 0 ? @response_rate = 0 : @response_rate = ((Conversation.organization(@organization.id).unique_calls_last_month(@this_org.phone_number).count.to_f/2)/@last_month.to_f)*100
    @undelivered_rate = Conversation.organization(@organization.id).undelivered_month.count >0? ((Conversation.organization(@organization.id).month_calls.count.to_f/2)/Conversation.organization(@organization.id).undelivered_month.count.to_f)*100 : 0

    respond_to do |format|
      format.html # index.html.erb
      format.json 
    end
  end

  def report
    notifications_scope = Conversation.organization(@organization.id)
    if !params[:searchfilter].nil? 
      notifications_scope = notifications_scope.like(params[:searchfilter]) if !params[:searchfilter].empty?
    end
    notifications_scope = notifications_scope.all_calls if params[:calls_check] == "1"
    notifications_scope = notifications_scope.undelivered if params[:undelivered_check] == "1"
    notifications_scope = notifications_scope.unsubscribed if params[:stop_check] == "1"
    notifications_scope = notifications_scope.all_sent if params[:messages_check] == "1"
    if params[:start_date] || params[:end_date]
      notifications_scope = notifications_scope.date_filter(start_date: params[:start_date], end_date: params[:end_date]) if !params[:start_date].empty? || !params[:end_date].empty?
    end
    @notifications = smart_listing_create(:notifications, notifications_scope, partial: "admin/dashboard/listing")
    @export_link = Base64.encode64(params.to_s)
    respond_to do |format|
      format.html # index.html.erb
      format.json 
      format.js
    end
    
  end

  def export
    @params = Base64.decode64(params[:options])
    if !@params.nil?
      @options_hash = JSON.parse @params.gsub('=>', ':')

      notifications_scope = Conversation.organization(@organization.id)
      if !@options_hash["searchfilter"].nil? 
        notifications_scope = notifications_scope.like(@options_hash["searchfilter"]) if !@options_hash["searchfilter"].empty?
      end
      notifications_scope = notifications_scope.all_calls if @options_hash["calls_check"] == "1"
      notifications_scope = notifications_scope.undelivered if @options_hash["undelivered_check"] == "1"
      notifications_scope = notifications_scope.unsubscribed if @options_hash["stop_check"] == "1"
      notifications_scope = notifications_scope.all_sent if @options_hash["messages_check"] == "1"
      if @options_hash["start_date"] || @options_hash["end_date"]
        notifications_scope = notifications_scope.date_filter(start_date: @options_hash["start_date"], end_date: @options_hash["end_date"]) if !@options_hash["start_date"].empty? || !@options_hash["end_date"].empty?
      end
    end
    respond_to do |format|
      format.csv { render text: notifications_scope.to_csv(notifications_scope) }
    end
  end

  def authorize
    raise CanCan::AccessDenied unless can? :read, Reminder, @organization_user
  end
end

app/views/admin/dashboard/_add_recipient.html.erb
<div class="control-group">
	<h3>Cell Phone Numbers of Recipients</h3>
	<% @recipient.each do |recipient| %>
	<p><%= recipient.phone %></p>
	<% end %>
	<%= link_to 'New recipient', new_organization_recipient_path(organization), :class => 'btn btn-primary' %>
</div>

app/views/admin/dashboard/_calls.html.erb
<div class="recentReminder">
	<%= content_tag :div, "", class: "chart", id: "calls_chart", data: {graph_data: chart_data(2.weeks.ago.to_date, "date", Conversation.unique_calls_last_month(@this_org.phone_number))} %>
</div>

app/views/admin/dashboard/_listing.html.erb
<% unless smart_listing.empty? %>
<div class="row">
  <div class="large-2 columns">
    <h4 class="">Total:&nbsp;<%= smart_listing.count %></h4>
  </div>
  <div class="large-5 large-offset-5 columns">
    <%= link_to 'EXPORT TABLE', admin_organization_dashboard_export_path(:options => @export_link, :format => :csv), :class => 'button primary small' %>
  </div>
</div>
<div>
  <table id="all_notifications" class="notification_table large-12 columns">
    <thead>
      <th><%= smart_listing.sortable "Status", "status" %></th>
      <th><%= smart_listing.sortable "#", "id" %></th>
      <th><%= smart_listing.sortable "Date", "date" %></th>
      <th><%= smart_listing.sortable "To", "to_number" %></th>
      <th><%= smart_listing.sortable "From", "from_number" %></th>
      <th><%= smart_listing.sortable "Message", "message" %></th>
    </thead>
    <tbody>
      <% smart_listing.collection.each do |o| %>
      <tr>
        <td><%= o.status %></td>
        <td><%= o.id %></td>
        <td><%= o.date.strftime('%D %r') %></td>
        <td><%= o.to_number.phony_formatted(:normalize => :US, :spaces => '-', :area_code => true) %></td>
        <td><%= o.from_number.phony_formatted(:normalize => :US, :spaces => '-', :area_code => true) %></td>
        <td><%= o.message %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= smart_listing.paginate %>
  <h5><%= smart_listing.pagination_per_page_links %></h5>
  <% else %>
  <br>
  <div class="text-center">
    <h3>Your search didn't match any requests.</h3>
    <p>Try different: search terms, statuses, or dates.</p>
  </div>
  <% end %>
</div>

app/views/admin/dashboard/_messages.html.erb
<tr>
	<td><p><%= recents.message %></p></td>
	<td><%= recents.date.to_s(:date_format) %></td>
	<td><%= recents.status %></td>
</tr>

app/views/admin/dashboard/_notifications.html.erb
<div>
	<table class="table tableGreen">
		<thead>
			<tr>
				<th>Message Type</th>
			</tr>
		</thead>
		<tr>
			<td><p><%= Reminder.find(upcoming.reminder_id).message_text %></p></td>
			<td><p>Sent to <%= link_to upcoming.to_number, recipient_path(upcoming.recipient_ids) %></p></td>
			<td><%= upcoming.date.to_s(:date_format) %></td>
			<td><i class="icon-pencil"></i></td>
		</tr>
	</table>
</div>

app/views/admin/dashboard/_responses.html.erb
<div class="recentReminder">
	<%= content_tag :div, "", class: "chart", id: "response_chart", data: {graph_data: chart_data(4.weeks.ago.to_date, "date", Conversation.organization(@organization.id).text_responses)} %>
</div>

app/views/admin/dashboard/_sent_reminders.html.erb
<div class="recentReminder">
	<%= content_tag :div, "", class: "chart", id: "sent_chart", data: {graph_data: chart_data(2.weeks.ago.to_date, "date", Conversation.organization(@organization.id))} %>
</div>

app/views/admin/dashboard/_undelivered.html.erb
<div class="recentReminder">
	<%= content_tag :div, "", class: "chart", id: "undelivered_chart", data: {graph_data: chart_data(2.weeks.ago.to_date, "date", Conversation.organization(@organization.id).undelivered)} %>
</div>

app/views/admin/dashboard/_upcoming_reminders.html.erb
<div class="recentReminder">
	<%= content_tag :div, "",class: "chart", id: "upcoming_chart", data: {graph_data: chart_data(Date.today, Date.today+2.weeks, "send_date", Reminder.organization(@organization.id).upcoming)} %>
</div>

app/views/admin/dashboard/index.html.erb
<div class="row">
  <div class="small-3 small-offset-9 columns">
    <%= link_to 'CREATE NOTIFICATION', new_admin_organization_reminder_path(@organization), :class => 'button' %>
  </div>
</div>
<div class="row">
  <div class="pageHeader small-12 twelve columns">
    <div class="headerBig heading">
      <h1>Dashboard</h1>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-6 six columns">
    <div class="headerSmall headerAqua">
      <span class="headerText">Upcoming reminders</span>
    </div>
      <div><%= link_to 'View all', admin_organization_reminders_path(@organization), :class => 'button secondary tiny right panel-btn' %></div>
    <div class="conversation">
      <%= render 'upcoming_reminders', object: @upcoming || 'There are no upcoming reminders' %>
    </div>
  </div>
  <div class="small-6 six columns">
    <div class="headerSmall headerGreen">
      <span class="headerText">Sent reminders</span>
    </div>
    <div><%= link_to 'View all', admin_organization_sent_reminders_path(@organization), :class => 'button secondary tiny right' %></div>
    <div class="conversation">
      <%= render 'sent_reminders', object: @conversations || 'There are no sent reminders' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-6 six columns">
    <div class="headerSmall headerGreen">
      <span class="headerText">Text Responses</span>
    </div>
    <div><%= link_to 'View all', admin_organization_conversations_path(@organization), :class => 'button secondary tiny right' %></div>
    <div class="conversation">
      <%= render 'responses' || 'There are no responses' %>
    </div>
  </div>
  <div class="small-6 six columns">
    <div class="headerSmall headerRed">
      <span class="headerText">Undelivered reminders</span>
    </div>
    <div><%= link_to 'View all', admin_organization_conversations_path(@organization), :class => 'button secondary tiny right' %></div>
    <div class="conversation">
      <%= render 'undelivered' || 'There are no upcoming reminders' %>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-6 six columns">
    <div class="headerSmall headerAqua">
      <span class="headerText">Call Responses</span>
    </div>
    <div><%= link_to 'View all', admin_organization_conversations_path(@organization), :class => 'button secondary tiny right panel-btn' %></div>
    <div class="conversation">
      <%= render 'calls' || 'There are no calls' %>
    </div>
  </div>
</div>

app/views/admin/dashboard/index.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :notifications %>

app/views/admin/dashboard/report.html.erb
<div class="row">
  <div class="pageHeader small-12 twelve columns">
    <div class="headerBig heading">
      <h1>Reports</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-3 medium-3 small-12 columns">
    <%= smart_listing_controls_for(:notifications) do %>
      <!-- # Add search box to form - it submits the form automatically on text change -->
    <ul class="side-nav large-12 columns">
      <li class="large-12 columns request_search">
        <h4>SEARCH:</h4>
        <div class="row collapse">
          <div class="small-10 columns">
            <%= text_field_tag :searchfilter, '', placeholder: "I'd like to find...", autocomplete: :on %>
          </div>
          <div class="small-2 columns">
            <button class="button postfix primary"><i class="fi-magnifying-glass"></i></button>
          </div>
        </div>
      </li>
      <hr>
      <li class="large-12 columns">
        <h4>REFINE SEARCH:</h4>
      </li>
      <li class="large-12 columns status_filter">
        <div class="checkbox row collapse">
          <div class="checkbox inline">
            <div>
              <%= hidden_field_tag :messages_check, "0", id: "cc" %>
              <%= check_box_tag :messages_check %>
              <span class="closed"><%= "Text Messages" %></span>
            </div>
            <div>
              <%= hidden_field_tag :calls_check, "0", id: "cc" %>
              <%= check_box_tag :calls_check %>
              <span class="closed"><%= "Calls" %></span>
            </div>
            <div>
              <%= hidden_field_tag :stop_check, "0", id: "st" %>
              <%= check_box_tag :stop_check %>
              <span class="stop"><%= "Stop Messages" %></span>
            </div>
            <div>
              <%= hidden_field_tag :undelivered_check, "0", id: "ds" %>
              <%= check_box_tag :undelivered_check %>
              <span class="undelivered"><%= "Undelivered Messages" %></span>
            </div>
          </div>
        </div>
      </li>
      <li class="large-12 columns">
        <h5>Notification Date</h5>
        <div class="row collapse">
          <div class="large-5 medium-5 small-5 columns">
            <%= text_field_tag :start_date, '', placeholder: "Start date", class: 'dateSelect' %>
          </div>
          <div class="Large-5 large-offset-1 medium-5 medium-offset-1 small-5 small-offset-1 columns end">
            <%= text_field_tag :end_date, '', placeholder: "End date", class: 'dateSelect'  %>
          </div>
        </div>
      </li>
    </ul>
  </div>
  <% end %>
  <div class="large-9 medium-9 small-9 columns end">
    <%= smart_listing_render :notifications  %>
  </div>
</div>

app/views/admin/dashboard/report.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :notifications %>