config/routes.rb
Promptly::Application.routes.draw do
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   :as => 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'pages#home'


  # match 'logout', :to => 'sessions#destroy', :as => "logout"
    authenticated :user do
      root :to => 'pages#home'
    end

  namespace :admin do
      as :super do
        root to: 'superdashboard#index', as: 'dashboard'
      end
      resources :superdashboard, only: [:index] do
        get :show_users
        get 'edit_user/:id', to: 'superdashboard#edit_user', as: :edit_user
        post 'edit_user/:id', to: 'superdashboard#update_user', as: :update_user
      end
    resources :organizations do
      match 'reminders#panel2a' => 'reminders#panel2a', :as => :sent_reminders
      match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
      match 'dashboard/report', :to => 'dashboard#report', :as => :report
      match 'dashboard/export(/:options)/notifications', :to => 'dashboard#export', :as => :dashboard_export
      resources :users
      resources :recipients
      resources :conversations
      resources :groups
      resources :messages
      resources :organizations
      resources :reminders do
        collection do
          post :confirm
        end
      end
    end

  end


  #project page
  match '/hsa'       => 'pages#hsa'
  match '/documents' => 'pages#documents'

  #autoresponse
  match '/handle-incoming-sms'  => 'auto_response#handle_incoming_sms'
  match '/handle-incoming-call' => 'auto_response#handle_incoming_call'
  match '/handle-input'         => 'auto_response#handle_input'
  match '/english-response'     => 'auto_response#english_response'
  match '/spanish-response'     => 'auto_response#spanish_response'
  match '/cantonese-response'   => 'auto_response#cantonese_response'
end

app/views/shared/_adminnav.html.erb
<% if current_user.is_super? %>
  <dl class="promptly-sub-nav">
    <dt class="name"><%= link_to "Admin", admin_dashboard_path %></dt>
     <span class="right-side">
      <%= content_tag(:dd, class: is_active?("admin")) do %>
        <%= link_to admin_superdashboard_show_users_path(1) do %>
          <i class="fi-torsos-all large"></i>&nbsp;Manage Users
        <% end %>
        <%= link_to admin_organizations_path do %>
          <i class="fi-list-thumbnails large"></i>&nbsp;Manage Organizations
        <% end %>
      <% end %>
    </span>
  </dl>
<% end %>

app/views/shared/_footer.erb
<!-- start footer-->
<div class="footer">
  <div class="row">
    <div class="small-1 column">
      <a href="http://www.postcode.io/promptly" target="_title"><h6>About</h6></a>
    </div>
    <div class="small-1 end column">
      <a href="https://promptlyio.zendesk.com/hc/en-us"><h6>Help</h6></a>
    </div>
    <div class="small-1 end column">
      <%= link_to "https://github.com/postcode/promptly/" do %>
      <h6>Github</h6>
    <% end %>  
    </div>
    <div class="small-3 column">
      <a href="mailto:promptly@postcode.io"><h6>promptly@postcode.io</h6></a>
    </div>
    <div class="small-2 column text-right">
      <p>delivered by</p>
      <a href="http://postcode.io" target="_title"><img src="http://pobox.herokuapp.com/images/postcode_logo_drkgray.png"></a>
    </div>
  </div>
</div>
<!-- end footer-->

app/views/shared/_home_footer.html.erb
<div class="row landing-footer">
    <div class="large-1 columns drk">
      <h6><strong><a href="http://www.postcode.io/static/content/promptly.pdf" target="_title">About</a></strong></h6>
    </div>
    <div class="large-1 columns drk">
      <h6><strong><a href="https://promptlyio.zendesk.com/hc/en-us">Help</a></strong></h6>
    </div>
    <div class="large-1 columns drk">
      <h6><strong><a href="https://github.com/postcode/promptly" target="_title">Github</a></strong></h6>
    </div>
    <div class="large-2 columns drk">
      <h6><strong><a href="mailto:promptly@postcode.io">promptly@postcode.io</a></strong></h6>
    </div>
    <div class="large-3 columns wht right ">
      <div class="">
        <small>
        <a href="https://www.flickr.com/photos/pat_ossa/6051457263" target="_title">source:flickr.com,</a> <a class="citation" href="https://creativecommons.org/licenses/by/2.0/" target="_title">CC by 2.0</a>
        </small>
      </div>
    </div>
  </div>

app/views/shared/_mainnav.erb
<nav class="top-bar" data-topbar>
	<ul class="title-area">
    <li class="name">
      <h1><%= link_to "Promptly", root_path, :class => "brand" %></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <% if current_user.organizations.count >1 %>
          <li><%= link_to "Welcome, #{current_user.name}", [:admin, current_user.organizations.first, current_user] %></li>
        <% else %>
          <li><%= link_to "Welcome, #{current_user.name}", [:admin, current_user.organizations.first, current_user] %></li>
        <% end %>
        <% if current_user.organizations.length > 0 %>
          <li class="has-flyout has-dropdown">
            <%= link_to "Your Organizations", admin_organizations_path, class: "flyout-toggle" %>
            <ul class="flyout dropdown">
              <% if current_user.is_super? %>
                <% Organization.order('name ASC').all.each do |organization| %>
                  <li>
                    <a tabindex="-1" href="#">
                      <%= link_to organization.name, [:admin, organization] %>
                    </a>
                  </li>
                <% end %>
              <% else %>
                <% current_user.organizations.each do |organization| %>
                  <li>
                    <a tabindex="-1" href="#">
                      <%= link_to organization.name, [:admin, organization] %>
                    </a>
                  </li>
                <% end %>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to 'Manage organizations', admin_organizations_path %></li>
            </ul>
          </li>
        <% end %>
        <% if current_user.is_super? %>
          <li><%= link_to "Admin", admin_dashboard_path %></li>
        <% end %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
	</div>
</nav>

app/views/shared/_messages.html.erb
<% if !notice.nil? %>
  <div data-alert class="alert-box secondary">
    <span class="notice"><%= notice %></span>
    <a href="#" class="close">&times;</a>
  </div>
<% elsif !alert.nil? %>
  <div data-alert class="alert-box warning">
    <span class="notice"><%= alert %></span>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/shared/_queued_reminders.erb
<p><%= link_to reminder.send_date.to_s(:date_format), admin_organization_reminder_path(@organization,reminder.id) %><br /></p>
<p><%= Message.exists?(id: reminder.message_id) ? Message.find(reminder.message_id).message_text : "no message" %></p>

app/views/shared/_show_conversation.html.erb
<div class="conversation-<%= which_sender(conversation.from_number) %>">
	<% if which_sender(conversation.from_number) == "self" %>
		<div class="avatar">
			<span class="typcn typcn-device-phone"></span>
		</div>
	<% else %>
		<div class="avatar">
			<span class="typcn typcn-user"></span>
		</div>
	<% end %>
	<p><strong><%= conversation.date.to_s(:date_format) %></strong></p>
	<p><%= conversation.message %></p>
</div>

app/views/shared/_subnav.html.erb
<dl class="promptly-sub-nav">
  <dt class="name"><%= link_to @organization.name, admin_organization_dashboard_path(@organization.id) %></dt>
  <span class="right-side">
    <%= content_tag(:dd, class: is_active?("dashboard")) do %>
      <%= link_to admin_organization_dashboard_path(@organization.id) do %>
        <i class="fi-home large"></i>&nbsp;Dashboard
      <% end %>
    <% end %>
    <%= content_tag(:dd, class: is_active?("reminders")) do %>
      <%= link_to admin_organization_reminders_path(@organization.id) do %>
        <i class="fi-clock large"></i>&nbsp;Notifications
      <% end %>
    <% end %>
    <%= content_tag(:dd, class: is_active?("messages")) do %>
      <%= link_to admin_organization_messages_path(@organization.id) do %>
        <i class="fi-background-color large"></i>&nbsp;Messages
      <% end %>
    <% end %>
    <%= content_tag(:dd, class: is_active?("groups")) do %>
      <%= link_to admin_organization_groups_path(@organization.id) do %>
        <i class="fi-torsos-all large"></i>&nbsp;Groups
      <% end %>
    <% end %>
    <%= content_tag(:dd, class: is_active?("conversations")) do %>
      <%= link_to admin_organization_conversations_path(@organization.id) do %>
        <i class="fi-comments large"></i>&nbsp;Conversations
      <% end %>
    <% end %>
    <%= content_tag(:dd, class: is_active?("report")) do %>
      <%= link_to admin_organization_report_path(@organization.id) do %>
        <i class="fi-comments large"></i>&nbsp;Reports
      <% end %>
    <% end %>
    <% if can? :manage, User %>
      <%= content_tag(:dd, class: is_active?("users")) do %>
        <%= link_to admin_organization_users_path(@organization.id) do %>
          <i class="fi-torso large"></i>&nbsp;Users
        <% end %>
      <% end %>
    <% end %>
  </span>
</dl>