config/routes.rb
Promptly::Application.routes.draw do
  
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   :as => 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', :as => 'user_registration'
  end

  root :to => 'pages#home'


  # match 'logout', :to => 'sessions#destroy', :as => "logout"
    authenticated :user do
      root :to => 'pages#home'
    end

  namespace :admin do
      as :super do
        root to: 'superdashboard#index', as: 'dashboard'
      end
      resources :superdashboard, only: [:index] do
        get :show_users
        get 'edit_user/:id', to: 'superdashboard#edit_user', as: :edit_user
        post 'edit_user/:id', to: 'superdashboard#update_user', as: :update_user
      end
    resources :organizations do
      match 'reminders#panel2a' => 'reminders#panel2a', :as => :sent_reminders
      match 'dashboard', :to => 'dashboard#index', :as => "dashboard"
      match 'dashboard/report', :to => 'dashboard#report', :as => :report
      match 'dashboard/export(/:options)/notifications', :to => 'dashboard#export', :as => :dashboard_export
      resources :users
      resources :recipients
      resources :conversations
      resources :groups
      resources :messages
      resources :organizations
      resources :reminders do
        collection do
          post :confirm
        end
      end
    end

  end


  #project page
  match '/hsa'       => 'pages#hsa'
  match '/documents' => 'pages#documents'

  #autoresponse
  match '/handle-incoming-sms'  => 'auto_response#handle_incoming_sms'
  match '/handle-incoming-call' => 'auto_response#handle_incoming_call'
  match '/handle-input'         => 'auto_response#handle_input'
  match '/english-response'     => 'auto_response#english_response'
  match '/spanish-response'     => 'auto_response#spanish_response'
  match '/cantonese-response'   => 'auto_response#cantonese_response'
end

app/models/organization.rb
class Organization < ActiveRecord::Base  
  attr_accessible :name, :user_ids, :recipient_ids, :conversation_ids, :group_ids, :message_ids, :reminder_ids, :organizations_user, :phone_number
  has_many :organizations_user
  has_many :users, through: :organizations_user
  validates_presence_of :name
  validates_plausible_phone :phone_number, presence: true
  validates :phone_number, uniqueness: true
  has_many :conversations
  has_many :groups
  has_many :messages
  has_many :reminders

  def to_param
    "#{self.id}"
  end

  def self.save_org_users(org_id, ids, roles)
    ids.each do |user_id|
      if user_id[1] == "1"
        @organization_user = OrganizationsUser.where(:organization_id => org_id, :user_id => user_id[0]).first_or_create
        @org_role = roles["#{user_id[0]}"]
        @organization_user.update_attributes(:roles_mask => OrganizationsUser.mask_for(@org_role[:roles_mask]))
        if !@organization_user.save
          @organization_user.errors.messages
        end
      else
        if OrganizationsUser.exists?(:organization_id => org_id, :user_id => user_id[0])
          OrganizationsUser.find(org_id, user_id[0]).delete
        end
      end
    end
  end

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  
  def index
    @organizations = Organization.all
  end
 
  def new
  	@organization = Organization.new
  end

  def show
    @organization = Organization.find(params[:id])
    redirect_to(admin_organization_dashboard_path(@organization.id))
  end

  def edit
    @organization = Organization.find(params[:id])
  end
 
  def destroy
    authorize
  	@organization = Organization.find(params[:id])

    if @organization.destroy
      redirect_to action: "index", notice: "Organization successfully deleted."
    else
      redirect_to admin_organizations_path
    end    
  end
 
  def create
    authorize
    @organization = Organization.new(params[:organization])
    if params[:organization][:phone_number].length <12
      @phone = "+1" + params[:organization][:phone_number]
      @organization.update_attributes(:phone_number => @phone)
    else
      @organization.update_attributes(:phone_number => params[:organization][:phone_number])
    end
    if @organization.save
      Organization.save_org_users(@organization.id, params[:organizations_user][:user_ids], params[:organizations_user])
      redirect_to admin_organizations_path 
    else
      render action: "new", status: "unprocessable_entity"
    end
  end

  def update
    authorize
    @organization = Organization.update(params[:id], params[:organization])
    if params[:organization][:phone_number].length <12 && params[:organization][:phone_number].length >0
      @phone = "+1" + params[:organization][:phone_number]
      @organization.update_attributes(:phone_number => @phone)
    else
      @organization.update_attributes(:phone_number => params[:organization][:phone_number])
    end
    
    if @organization.save
      Organization.save_org_users(@organization.id, params[:organizations_user][:user_ids], params[:organizations_user])
      redirect_to admin_organizations_path
    else
      render action: "edit", status: "unprocessable_entity"
    end
  end

  def authorize
    if !@current_user.is_super? 
      raise CanCan::AccessDenied 
    end
  end

end

app/views/admin/organizations/_form.html.erb
<%= simple_form_for [:admin, @organization] do |f| %>
  <%= f.input :name, inline_label: "Name" %>
  <%= f.input :phone_number, inline_label: "Phone Number" %>
  <% f.association :users, as: :check_boxes, label: "Users" %>
 <div class="row">
  <div class="small-12 twelve columns">
    <table class="table table-hover datatable small-12 twelve" id="add-groups">
      <thead>
        <tr>
          <th>Add to Organization</th>
          <th>Name</th>
          <th>Role</th>
        </tr>
      </thead>
      <tbody>
        <% for user in User.all %>
        <tr>
          <% if OrganizationsUser.exists?(:organization_id => @organization.id, :user_id => user.id) %>
            <td><%= check_box "organizations_user[user_ids]", user.id, :class => 'table-row-checkbox', checked: true %></td>
          <% else %>
            <td><%= check_box "organizations_user[user_ids]", user.id, :class => 'table-row-checkbox' %></td>
          <% end %>
          <td><%= user.name %></td>
          <td><%= simple_fields_for :organizations_user do |org_user| %>
          <div class="field">
              <div class="control-group">
                <div class="controls">
                  <% role = OrganizationsUser.where(:organization_id => @organization.id, :user_id => user.id) %>
                  <% if role.exists? %>
                    <%= org_user.collection_select "#{user.id}[roles_mask]", OrganizationsUser.valid_roles, :to_s, :to_s, {:selected => role[0].roles.first} %>
                  <% else %>
                    <%= org_user.collection_select "#{user.id}[roles_mask]", OrganizationsUser.valid_roles, :to_s, :to_s, {:selected => 'user'} %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %></td>
        </tr>
        <% end %>
        <tr>
          <td></td>
          <td></td>
          <% if @organization.id? %>
            <td><%= link_to_if (@current_user.has_any_role? :admin, :super), "Create a new user", new_admin_organization_user_path(@organization.id), :class => 'button secondary tiny'%> </td>
          <% else %>
            <td> </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
</div>
  
  <%= f.button :submit, :class => 'button small' %>
  <%= link_to_if (@current_user.has_any_role? :admin, :super), "Delete this organization", [:admin, @organization], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button alert small right' -%>
  
<% end %>

app/views/admin/organizations/_roles.html.erb
<%= simple_fields_for :organizations_user do |org_user| %>
<div class="field">
    <div class="control-group">
      <%= org_user.label :roles, 'Select a role' %>
      <div class="controls">
        <%= org_user.collection_select "organizations_user[user_ids][roles]", OrganizationsUser.valid_roles, :to_s, :to_s %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/organizations/edit.html.erb
<h2>Edit Organization</h2>

<%= render partial: "form", object: @organization %>

app/views/admin/organizations/index.html.erb
<div class="heading">
  <h1>Your organizations</h1>
</div>
<ul class="list-unstyled">
<% if current_user.is_super? %>
  <% Organization.order('name ASC').all.each do |organization| %>
      <li><%= link_to organization.name, [:admin, organization] %>&nbsp;<%= link_to "Edit", [:edit, :admin, organization], class: "button secondary" %></li>
  <% end %>
<% else %>
  <% current_user.organizations.each do |organization| %>
      <li><%= link_to organization.name, [:admin, organization] %></li>
  <% end %>
<% end %>
</ul>

<% if current_user.is_super? %>
  <%= link_to 'Create organization', new_admin_organization_path, :class => 'button' %>
<% end %>

app/views/admin/organizations/new.html.erb
<h2>New Organization</h2>

<%= render partial: "form", object: @organization %>

app/views/admin/organizations/show.html.erb
<div id="sidebar-left" class="small-2 two columns">
  <%= render 'layouts/sidebar' %>
</div>
<div class="org-container small-10 ten columns">
  <div class="row">
    <div>
      <h1><%= @organization.name -%></h1>
      <span class="pageTitle small-3 three">All Users</span>
      <% if @organization.users.any? %>
      <table class="table table-striped small-8 eight">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <% @organization.users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.email -%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <p>There currently aren't any users in this organization. <%= link_to "Add some!", new_admin_organization_user_path(@organization.id) -%>
      <% end %>
    </div>
  </div>
  <div class="row">
    <%= link_to "Edit this organization", edit_admin_organization_path(@organization.id), :class => 'btn btn-primary' %>
    <%= link_to "Delete this organization", admin_organization_path(@organization.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' -%>
  </div>
</div>